/**
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo1.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class OO1DescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
