/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package com.poli.ads.oo1.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class OO1OutlineTreeProvider extends DefaultOutlineTreeProvider {
}
