/*
 * generated by Xtext 2.13.0
 */
package com.poli.ads.expressoes2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Expressoes2StandaloneSetup extends Expressoes2StandaloneSetupGenerated {

	def static void doSetup() {
		new Expressoes2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
