/*
 * generated by Xtext 2.13.0
 */
package com.poli.ads.expressoes2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Expressoes2RuntimeModule extends AbstractExpressoes2RuntimeModule {
}
