/*
 * generated by Xtext 2.13.0
 */
package com.poli.ads.imperativa2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Imperativa2StandaloneSetup extends Imperativa2StandaloneSetupGenerated {

	def static void doSetup() {
		new Imperativa2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
