/*
 * generated by Xtext 2.13.0
 */
package com.poli.ads.imperativa2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Imperativa2RuntimeModule extends AbstractImperativa2RuntimeModule {
}
