/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional3


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Funcional3RuntimeModule extends AbstractFuncional3RuntimeModule {
}
