/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional3


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Funcional3StandaloneSetup extends Funcional3StandaloneSetupGenerated {

	def static void doSetup() {
		new Funcional3StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
