/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.imperativa1.ide


/**
 * Use this class to register ide components.
 */
class Imperativa1IdeModule extends AbstractImperativa1IdeModule {
}
