/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Funcional2StandaloneSetup extends Funcional2StandaloneSetupGenerated {

	def static void doSetup() {
		new Funcional2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
