/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Funcional1StandaloneSetup extends Funcional1StandaloneSetupGenerated {

	def static void doSetup() {
		new Funcional1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
