/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Funcional1RuntimeModule extends AbstractFuncional1RuntimeModule {
}
