/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo1


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OO1RuntimeModule extends AbstractOO1RuntimeModule {
}
