/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo1.ide

import com.google.inject.Guice
import com.poli.ads.oo1.OO1RuntimeModule
import com.poli.ads.oo1.OO1StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class OO1IdeSetup extends OO1StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new OO1RuntimeModule, new OO1IdeModule))
	}
	
}
