/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.expressoes1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Expressoes1StandaloneSetup extends Expressoes1StandaloneSetupGenerated {

	def static void doSetup() {
		new Expressoes1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
