/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.expressoes1


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Expressoes1RuntimeModule extends AbstractExpressoes1RuntimeModule {
}
