/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.imperativa1.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Imperativa1ProposalProvider extends AbstractImperativa1ProposalProvider {
}
