/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.expressoes1.ide


/**
 * Use this class to register ide components.
 */
class Expressoes1IdeModule extends AbstractExpressoes1IdeModule {
}
