/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Funcional1UiModule extends AbstractFuncional1UiModule {
}
