/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OO2RuntimeModule extends AbstractOO2RuntimeModule {
}
