/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OO2StandaloneSetup extends OO2StandaloneSetupGenerated {

	def static void doSetup() {
		new OO2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
