/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Funcional2UiModule extends AbstractFuncional2UiModule {
}
