/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo2.ide

import com.google.inject.Guice
import com.poli.ads.oo2.OO2RuntimeModule
import com.poli.ads.oo2.OO2StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class OO2IdeSetup extends OO2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new OO2RuntimeModule, new OO2IdeModule))
	}
	
}
