/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.funcional3.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Funcional3ProposalProvider extends AbstractFuncional3ProposalProvider {
}
