/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package com.poli.ads.oo1.ui.contentassist;

import com.poli.ads.oo1.ui.contentassist.AbstractOO1ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OO1ProposalProvider extends AbstractOO1ProposalProvider {
}
