/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.oo2.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class OO2ScopeProvider extends AbstractOO2ScopeProvider {

}
