/*
 * generated by Xtext 2.13.0
 */
package com.poli.ads.expressoes2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Expressoes2UiModule extends AbstractExpressoes2UiModule {
}
