/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.imperativa1.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Imperativa1UiModule extends AbstractImperativa1UiModule {
}
