/*
 * generated by Xtext 2.12.0
 */
package com.poli.ads.expressoes1.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Expressoes1UiModule extends AbstractExpressoes1UiModule {
}
